name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: iiXXiXii
          svg_out_path: dist/snake.svg
          snake_color: "#3a7bd5"
          date_format: "%Y-%m-%d"
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
